kind: Deployment
apiVersion: apps/v1
metadata:
  name: backstage-springboot-gpt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backstage-springboot-gpt
  template:
    metadata:
      labels:
        app: backstage-springboot-gpt
    spec:
      containers:
        - name: backstage-springboot-gpt
          image: quay.io/backstage-springboot-gpt/backstage-springboot-gpt:latest
          ports:
            - name: http-5000
              containerPort: 5000
              protocol: TCP
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
