kind: Service
apiVersion: v1
metadata:
  name: backstage-springboot-gpt
spec:
  ports:
    - name: http-5000
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: backstage-springboot-gpt
