apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "backstage-springboot-gpt"
spec:
  destination:
    namespace: schultzp2020
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/base
    repoURL: https://github.com/schultzp2020/backstage-springboot-gpt
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
